// Code generated by mockery v1.0.0. DO NOT EDIT.

package modem

import context "context"
import mock "github.com/stretchr/testify/mock"
import runner "github.com/open-integration/open-integration/core/service/runner"

// MockModem is an autogenerated mock type for the Modem type
type MockModem struct {
	mock.Mock
}

// AddService provides a mock function with given fields: name, _a1
func (_m *MockModem) AddService(name string, _a1 runner.Service) error {
	ret := _m.Called(name, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, runner.Service) error); ok {
		r0 = rf(name, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Call provides a mock function with given fields: ctx, service, endpoint, arguments, fd
func (_m *MockModem) Call(ctx context.Context, service string, endpoint string, arguments map[string]interface{}, fd string) ([]byte, error) {
	ret := _m.Called(ctx, service, endpoint, arguments, fd)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]interface{}, string) []byte); ok {
		r0 = rf(ctx, service, endpoint, arguments, fd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, map[string]interface{}, string) error); ok {
		r1 = rf(ctx, service, endpoint, arguments, fd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Destroy provides a mock function with given fields:
func (_m *MockModem) Destroy() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Init provides a mock function with given fields:
func (_m *MockModem) Init() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
