// Code generated by mockery 2.7.5. DO NOT EDIT.

package modem

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockServiceCaller is an autogenerated mock type for the ServiceCaller type
type MockServiceCaller struct {
	mock.Mock
}

// Call provides a mock function with given fields: ctx, service, endpoint, arguments, fd
func (_m *MockServiceCaller) Call(ctx context.Context, service string, endpoint string, arguments map[string]interface{}, fd string) ([]byte, error) {
	ret := _m.Called(ctx, service, endpoint, arguments, fd)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]interface{}, string) []byte); ok {
		r0 = rf(ctx, service, endpoint, arguments, fd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, map[string]interface{}, string) error); ok {
		r1 = rf(ctx, service, endpoint, arguments, fd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
