// Code generated by mockery 2.7.5. DO NOT EDIT.

package reporter

import mock "github.com/stretchr/testify/mock"

// MockEventReporter is an autogenerated mock type for the EventReporter type
type MockEventReporter struct {
	mock.Mock
}

// Report provides a mock function with given fields: _a0, _a1
func (_m *MockEventReporter) Report(_a0 string, _a1 interface{}) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
