// Code generated by mockery 2.7.5. DO NOT EDIT.

package condition

import (
	event "github.com/open-integration/oi/core/event"
	mock "github.com/stretchr/testify/mock"

	state "github.com/open-integration/oi/core/state"
)

// MockCondition is an autogenerated mock type for the Condition type
type MockCondition struct {
	mock.Mock
}

// Met provides a mock function with given fields: ev, s
func (_m *MockCondition) Met(ev event.Event, s state.State) bool {
	ret := _m.Called(ev, s)

	var r0 bool
	if rf, ok := ret.Get(0).(func(event.Event, state.State) bool); ok {
		r0 = rf(ev, s)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
