// Code generated by mockery 2.7.5. DO NOT EDIT.

package downloader

import mock "github.com/stretchr/testify/mock"

// MockDownloader is an autogenerated mock type for the Downloader type
type MockDownloader struct {
	mock.Mock
}

// Download provides a mock function with given fields: name, version
func (_m *MockDownloader) Download(name string, version string) (string, error) {
	ret := _m.Called(name, version)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(name, version)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(name, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
