// Code generated by mockery 2.7.5. DO NOT EDIT.

package engine

import (
	modem "github.com/open-integration/oi/core/modem"
	mock "github.com/stretchr/testify/mock"
)

// MockEngine is an autogenerated mock type for the Engine type
type MockEngine struct {
	mock.Mock
}

// Modem provides a mock function with given fields:
func (_m *MockEngine) Modem() modem.Modem {
	ret := _m.Called()

	var r0 modem.Modem
	if rf, ok := ret.Get(0).(func() modem.Modem); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(modem.Modem)
		}
	}

	return r0
}

// Run provides a mock function with given fields:
func (_m *MockEngine) Run() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
