// Code generated by mockery v1.0.0. DO NOT EDIT.

package modem

import io "io"
import mock "github.com/stretchr/testify/mock"

// mockServiceStarter is an autogenerated mock type for the serviceStarter type
type mockServiceStarter struct {
	mock.Mock
}

// Exec provides a mock function with given fields: command, args, environ, detached, workingDir, binpath, logger
func (_m *mockServiceStarter) Exec(command string, args []string, environ []string, detached bool, workingDir string, binpath string, logger io.Writer) (int, error) {
	ret := _m.Called(command, args, environ, detached, workingDir, binpath, logger)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, []string, []string, bool, string, string, io.Writer) int); ok {
		r0 = rf(command, args, environ, detached, workingDir, binpath, logger)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, []string, []string, bool, string, string, io.Writer) error); ok {
		r1 = rf(command, args, environ, detached, workingDir, binpath, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
