// Code generated by mockery v1.0.0. DO NOT EDIT.

package modem

import io "io"
import mock "github.com/stretchr/testify/mock"

// mockFileCreator is an autogenerated mock type for the fileCreator type
type mockFileCreator struct {
	mock.Mock
}

// Create provides a mock function with given fields: dir, name
func (_m *mockFileCreator) Create(dir string, name string) (io.Writer, error) {
	ret := _m.Called(dir, name)

	var r0 io.Writer
	if rf, ok := ret.Get(0).(func(string, string) io.Writer); ok {
		r0 = rf(dir, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(dir, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
