// Code generated by mockery v1.0.0. DO NOT EDIT.

package modem

import grpc "google.golang.org/grpc"
import mock "github.com/stretchr/testify/mock"
import v1 "github.com/open-integration/core/pkg/api/v1"

// mockServiceClientCreator is an autogenerated mock type for the serviceClientCreator type
type mockServiceClientCreator struct {
	mock.Mock
}

// New provides a mock function with given fields: cc
func (_m *mockServiceClientCreator) New(cc *grpc.ClientConn) v1.ServiceClient {
	ret := _m.Called(cc)

	var r0 v1.ServiceClient
	if rf, ok := ret.Get(0).(func(*grpc.ClientConn) v1.ServiceClient); ok {
		r0 = rf(cc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.ServiceClient)
		}
	}

	return r0
}
