// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

//lint:file-ignore SA1019 generated code

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_OK    Status = 0
	Status_Error Status = 1
)

var Status_name = map[int32]string{
	0: "OK",
	1: "Error",
}

var Status_value = map[string]int32{
	"OK":    0,
	"Error": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}

type InitRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitRequest) Reset()         { *m = InitRequest{} }
func (m *InitRequest) String() string { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()    {}
func (*InitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}

func (m *InitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRequest.Unmarshal(m, b)
}
func (m *InitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRequest.Marshal(b, m, deterministic)
}
func (m *InitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRequest.Merge(m, src)
}
func (m *InitRequest) XXX_Size() int {
	return xxx_messageInfo_InitRequest.Size(m)
}
func (m *InitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRequest proto.InternalMessageInfo

type InitResponse struct {
	JsonSchemas          map[string]string `protobuf:"bytes,1,rep,name=jsonSchemas,proto3" json:"jsonSchemas,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InitResponse) Reset()         { *m = InitResponse{} }
func (m *InitResponse) String() string { return proto.CompactTextString(m) }
func (*InitResponse) ProtoMessage()    {}
func (*InitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{1}
}

func (m *InitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitResponse.Unmarshal(m, b)
}
func (m *InitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitResponse.Marshal(b, m, deterministic)
}
func (m *InitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitResponse.Merge(m, src)
}
func (m *InitResponse) XXX_Size() int {
	return xxx_messageInfo_InitResponse.Size(m)
}
func (m *InitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitResponse proto.InternalMessageInfo

func (m *InitResponse) GetJsonSchemas() map[string]string {
	if m != nil {
		return m.JsonSchemas
	}
	return nil
}

type CallRequest struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Arguments            string   `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Fd                   string   `protobuf:"bytes,3,opt,name=fd,proto3" json:"fd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallRequest) Reset()         { *m = CallRequest{} }
func (m *CallRequest) String() string { return proto.CompactTextString(m) }
func (*CallRequest) ProtoMessage()    {}
func (*CallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2}
}

func (m *CallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallRequest.Unmarshal(m, b)
}
func (m *CallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallRequest.Marshal(b, m, deterministic)
}
func (m *CallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallRequest.Merge(m, src)
}
func (m *CallRequest) XXX_Size() int {
	return xxx_messageInfo_CallRequest.Size(m)
}
func (m *CallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CallRequest proto.InternalMessageInfo

func (m *CallRequest) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *CallRequest) GetArguments() string {
	if m != nil {
		return m.Arguments
	}
	return ""
}

func (m *CallRequest) GetFd() string {
	if m != nil {
		return m.Fd
	}
	return ""
}

type CallResponse struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=v1.Status" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Payload              string   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallResponse) Reset()         { *m = CallResponse{} }
func (m *CallResponse) String() string { return proto.CompactTextString(m) }
func (*CallResponse) ProtoMessage()    {}
func (*CallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{3}
}

func (m *CallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallResponse.Unmarshal(m, b)
}
func (m *CallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallResponse.Marshal(b, m, deterministic)
}
func (m *CallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallResponse.Merge(m, src)
}
func (m *CallResponse) XXX_Size() int {
	return xxx_messageInfo_CallResponse.Size(m)
}
func (m *CallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CallResponse proto.InternalMessageInfo

func (m *CallResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *CallResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CallResponse) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func init() {
	proto.RegisterEnum("v1.Status", Status_name, Status_value)
	proto.RegisterType((*InitRequest)(nil), "v1.InitRequest")
	proto.RegisterType((*InitResponse)(nil), "v1.InitResponse")
	proto.RegisterMapType((map[string]string)(nil), "v1.InitResponse.JsonSchemasEntry")
	proto.RegisterType((*CallRequest)(nil), "v1.CallRequest")
	proto.RegisterType((*CallResponse)(nil), "v1.CallResponse")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_f7e43720d1edc0fe) }

var fileDescriptor_f7e43720d1edc0fe = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x41, 0x4f, 0xfa, 0x40,
	0x10, 0xc5, 0xff, 0x2d, 0x7f, 0x8a, 0x4c, 0x11, 0x9b, 0x89, 0x87, 0x06, 0x3d, 0x60, 0x4f, 0xe8,
	0xa1, 0x09, 0x78, 0x31, 0x1e, 0xbc, 0x10, 0x0e, 0xea, 0xc1, 0xa4, 0x1c, 0x3c, 0x9a, 0xa5, 0x0c,
	0x5a, 0x2d, 0xbb, 0x75, 0x77, 0xdb, 0x84, 0xcf, 0xe1, 0x17, 0x36, 0xdd, 0x2d, 0xd2, 0x70, 0xeb,
	0x7b, 0xfd, 0xcd, 0xcb, 0xbc, 0x59, 0x80, 0x54, 0x48, 0x8a, 0x0b, 0x29, 0xb4, 0x40, 0xb7, 0x9a,
	0x46, 0xa7, 0xe0, 0x3f, 0xf2, 0x4c, 0x27, 0xf4, 0x5d, 0x92, 0xd2, 0xd1, 0x8f, 0x03, 0x03, 0xab,
	0x55, 0x21, 0xb8, 0x22, 0x9c, 0x83, 0xff, 0xa9, 0x04, 0x5f, 0xa6, 0x1f, 0xb4, 0x65, 0x2a, 0x74,
	0xc6, 0x9d, 0x89, 0x3f, 0xbb, 0x8a, 0xab, 0x69, 0xdc, 0xc6, 0xe2, 0xa7, 0x03, 0xb3, 0xe0, 0x5a,
	0xee, 0x92, 0xf6, 0xd4, 0xe8, 0x01, 0x82, 0x63, 0x00, 0x03, 0xe8, 0x7c, 0xd1, 0x2e, 0x74, 0xc6,
	0xce, 0xa4, 0x9f, 0xd4, 0x9f, 0x78, 0x0e, 0xdd, 0x8a, 0xe5, 0x25, 0x85, 0xae, 0xf1, 0xac, 0xb8,
	0x77, 0xef, 0x9c, 0xe8, 0x15, 0xfc, 0x39, 0xcb, 0xf3, 0x66, 0x49, 0x1c, 0xc1, 0x09, 0xf1, 0x75,
	0x21, 0x32, 0xae, 0x9b, 0xf9, 0x3f, 0x8d, 0x97, 0xd0, 0x67, 0xf2, 0xbd, 0xdc, 0x12, 0xd7, 0xaa,
	0x09, 0x3a, 0x18, 0x38, 0x04, 0x77, 0xb3, 0x0e, 0x3b, 0xc6, 0x76, 0x37, 0xeb, 0x68, 0x05, 0x03,
	0x1b, 0xdc, 0xb4, 0x8d, 0xc0, 0x53, 0x9a, 0xe9, 0x52, 0x99, 0xdc, 0xe1, 0x0c, 0xea, 0xa2, 0x4b,
	0xe3, 0x24, 0xcd, 0x9f, 0x7a, 0x4d, 0x92, 0x52, 0xc8, 0xfd, 0x9a, 0x46, 0x60, 0x08, 0xbd, 0x82,
	0xed, 0x72, 0xc1, 0xf6, 0xf1, 0x7b, 0x79, 0x73, 0x01, 0x9e, 0x4d, 0x40, 0x0f, 0xdc, 0x97, 0xe7,
	0xe0, 0x1f, 0xf6, 0xa1, 0xbb, 0xa8, 0x87, 0x02, 0x67, 0xf6, 0x06, 0xbd, 0x25, 0xc9, 0x2a, 0x4b,
	0x09, 0xaf, 0xe1, 0x7f, 0xc6, 0x33, 0x8d, 0x67, 0x87, 0xe3, 0x9a, 0xba, 0xa3, 0xe0, 0xf8, 0xda,
	0x35, 0x9a, 0xb2, 0x3c, 0xb7, 0x68, 0xeb, 0x32, 0x16, 0x6d, 0x37, 0x5a, 0x79, 0xe6, 0xa9, 0x6f,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x11, 0x4f, 0x14, 0x86, 0xf8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, "/v1.Service/init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, "/v1.Service/call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	Init(context.Context, *InitRequest) (*InitResponse, error)
	Call(context.Context, *CallRequest) (*CallResponse, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) Init(ctx context.Context, req *InitRequest) (*InitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (*UnimplementedServiceServer) Call(ctx context.Context, req *CallRequest) (*CallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Service/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Service/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "init",
			Handler:    _Service_Init_Handler,
		},
		{
			MethodName: "call",
			Handler:    _Service_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core.proto",
}
