// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import grpc "google.golang.org/grpc"
import mock "github.com/stretchr/testify/mock"
import v1 "github.com/open-integration/core/pkg/api/v1"

// ServiceClient is an autogenerated mock type for the ServiceClient type
type ServiceClient struct {
	mock.Mock
}

// Call provides a mock function with given fields: ctx, in, opts
func (_m *ServiceClient) Call(ctx context.Context, in *v1.CallRequest, opts ...grpc.CallOption) (*v1.CallResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *v1.CallResponse
	if rf, ok := ret.Get(0).(func(context.Context, *v1.CallRequest, ...grpc.CallOption) *v1.CallResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.CallResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1.CallRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields: ctx, in, opts
func (_m *ServiceClient) Init(ctx context.Context, in *v1.InitRequest, opts ...grpc.CallOption) (*v1.InitResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *v1.InitResponse
	if rf, ok := ret.Get(0).(func(context.Context, *v1.InitRequest, ...grpc.CallOption) *v1.InitResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.InitResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1.InitRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
