// Code generated by mockery 2.7.5. DO NOT EDIT.

package runner

import (
	exec "os/exec"

	mock "github.com/stretchr/testify/mock"
)

// mockCmdCreator is an autogenerated mock type for the cmdCreator type
type mockCmdCreator struct {
	mock.Mock
}

// AddCommand provides a mock function with given fields: cmd
func (_m *mockCmdCreator) AddCommand(cmd string) {
	_m.Called(cmd)
}

// AddEnv provides a mock function with given fields: key, value
func (_m *mockCmdCreator) AddEnv(key string, value string) {
	_m.Called(key, value)
}

// Bin provides a mock function with given fields: path
func (_m *mockCmdCreator) Bin(path string) {
	_m.Called(path)
}

// Create provides a mock function with given fields:
func (_m *mockCmdCreator) Create() *exec.Cmd {
	ret := _m.Called()

	var r0 *exec.Cmd
	if rf, ok := ret.Get(0).(func() *exec.Cmd); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exec.Cmd)
		}
	}

	return r0
}
