// Code generated by mockery 2.7.5. DO NOT EDIT.

package runner

import (
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// mockDialer is an autogenerated mock type for the dialer type
type mockDialer struct {
	mock.Mock
}

// Dial provides a mock function with given fields: target, opts
func (_m *mockDialer) Dial(target string, opts ...grpc.DialOption) (*grpc.ClientConn, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, target)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *grpc.ClientConn
	if rf, ok := ret.Get(0).(func(string, ...grpc.DialOption) *grpc.ClientConn); ok {
		r0 = rf(target, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc.ClientConn)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, ...grpc.DialOption) error); ok {
		r1 = rf(target, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
