// Code generated by mockery 2.7.5. DO NOT EDIT.

package runner

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// mockLogFileCreator is an autogenerated mock type for the logFileCreator type
type mockLogFileCreator struct {
	mock.Mock
}

// Create provides a mock function with given fields: dir, name
func (_m *mockLogFileCreator) Create(dir string, name string) (io.Writer, error) {
	ret := _m.Called(dir, name)

	var r0 io.Writer
	if rf, ok := ret.Get(0).(func(string, string) io.Writer); ok {
		r0 = rf(dir, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(dir, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
