// Code generated by mockery 2.7.5. DO NOT EDIT.

package runner

import mock "github.com/stretchr/testify/mock"

// MockKiller is an autogenerated mock type for the Killer type
type MockKiller struct {
	mock.Mock
}

// Kill provides a mock function with given fields:
func (_m *MockKiller) Kill() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
