// Code generated by mockery 2.7.5. DO NOT EDIT.

package runner

import (
	context "context"

	v1 "github.com/open-integration/oi/pkg/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockCaller is an autogenerated mock type for the Caller type
type MockCaller struct {
	mock.Mock
}

// Call provides a mock function with given fields: _a0, req
func (_m *MockCaller) Call(_a0 context.Context, req *v1.CallRequest) (*v1.CallResponse, error) {
	ret := _m.Called(_a0, req)

	var r0 *v1.CallResponse
	if rf, ok := ret.Get(0).(func(context.Context, *v1.CallRequest) *v1.CallResponse); ok {
		r0 = rf(_a0, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.CallResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1.CallRequest) error); ok {
		r1 = rf(_a0, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
