// Code generated by mockery 2.7.5. DO NOT EDIT.

package runner

import (
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"

	v1 "github.com/open-integration/oi/pkg/api/v1"
)

// mockServiceClientCreator is an autogenerated mock type for the serviceClientCreator type
type mockServiceClientCreator struct {
	mock.Mock
}

// New provides a mock function with given fields: cc
func (_m *mockServiceClientCreator) New(cc *grpc.ClientConn) v1.ServiceClient {
	ret := _m.Called(cc)

	var r0 v1.ServiceClient
	if rf, ok := ret.Get(0).(func(*grpc.ClientConn) v1.ServiceClient); ok {
		r0 = rf(cc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.ServiceClient)
		}
	}

	return r0
}
