// Code generated by mockery 2.7.5. DO NOT EDIT.

package service

import (
	context "context"

	logger "github.com/open-integration/oi/pkg/logger"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/open-integration/oi/pkg/api/v1"
)

// mockEndpointHandler is an autogenerated mock type for the endpointHandler type
type mockEndpointHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, lgr, svc, req
func (_m *mockEndpointHandler) Execute(ctx context.Context, lgr logger.Logger, svc *Service, req *v1.CallRequest) (*v1.CallResponse, error) {
	ret := _m.Called(ctx, lgr, svc, req)

	var r0 *v1.CallResponse
	if rf, ok := ret.Get(0).(func(context.Context, logger.Logger, *Service, *v1.CallRequest) *v1.CallResponse); ok {
		r0 = rf(ctx, lgr, svc, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.CallResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, logger.Logger, *Service, *v1.CallRequest) error); ok {
		r1 = rf(ctx, lgr, svc, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
